// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuadzdchzfznhseususb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51YWR6ZGNoemZ6bmhzZXVzdXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMzgwMzksImV4cCI6MjA4ODkxNDAzOX0.yWuIQ1a1mqLOOb7Efs71bsTzBhjdbp-QrJcsdXOmf6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});